name: Weather Data Extraction Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_FILE: "weather.db"
  OUTPUT_FILE_NAME: "formatdata2.csv"  # You can change this dynamically later

jobs:
  weather-data-extraction:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Run your Python script
      - name: Run Weather Data Extraction
        run: |
          python ExtractTempHumidity.py
        env:
          DB_FILE: ${{ env.DB_FILE }}
          OUTPUT_FILE_NAME: ${{ env.OUTPUT_FILE_NAME }}
      
      # Step 4: Upload the output file as an artifact (optional)
      - name: Upload output CSV file
        uses: actions/upload-artifact@v4
        with:
          name: weather-data
          path: ${{ env.OUTPUT_FILE_NAME }}
